/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Contract {
  mission_id: string;
  version: number;
  hash: string;
  start_node: string;
  nodes: {
    [k: string]: ContractNode;
  };
}
export interface ContractNode {
  type: string;
  data?: unknown;
  next: string[];
}
