FROM golang:1.25-bookworm

WORKDIR /app

RUN go install github.com/air-verse/air@v1.65.3 \
  && go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
